### ISSUE TITLE
Let dstrsplit remove nul characters

### ISSUE THREAD

**Issue by kaneplusplus** [s-u/iotools#22]
```{r}
library(iotools)
download.file("http://euler.stat.yale.edu/~mjk56/fix_sample.tsv", "fix_sample.tsv")
dstrsplit(read.chunk(chunk.reader("fix_sample.tsv")), col_types=rep("character", 46))
```
produces the error message ```embedded nul in string```. It would be nice if ```dstrsplit``` could do this for us.

**Comment by statsmaths** [comment]
This does not cause any issues if you set the `col_types` to something other than characters; I believe the error is occurring in this line: [split_df.c#L197](https://github.com/s-u/iotools/blob/master/src/split_df.c#L197). Is your suggestion to remove anything following a nul char? That could be achieved by modifying the code to this:
```{c}
c2 = memchr(l,'\0',c-l);
if (c2 == NULL) c2 = c;
SET_STRING_ELT(VECTOR_ELT(sOutput, j), k, Rf_mkCharLen(l, c2 - l));
```
It fixes the error in your code at least. If that's the intended behavior, I can push this change into the code.

**Comment by s-u** [comment]
That seems like an overkill IMHO - embedded NULs are not supported by R and in non-encoded form neither in most other tools, so I'm reluctant to add scans in every string just to detect such unlikely occurrence. You can easily detect that in the incoming data if you expect it. At most, I'd make it an option, but not a default behavior since it's better to fail since something is terribly wrong with your data input in the first place.

**Comment by statsmaths** [comment]
Having a bit of time to think this over, I agree that it probably is best to thrown an error when encountered.
