### ISSUE TITLE
Add a prefetch parameter to imstrsplit

### ISSUE THREAD

**Issue by kaneplusplus** [s-u/iotools#28]
`imstrsplit` should have a prefetch function so that subsequent chunks can be requested when run in a `foreach` loop.

**Comment by s-u** [comment]
What do you mean? Since we're working on general connections it makes no sense to prefetch anything since you'll just double the fetch time for the first block as you can't do it parallel.

One thing we could do is to support some alternative back-end of ours where we use threads to do I/O and thus can prefetch. In fact, we could even implement that as a special "binary-only" connection type - thus somewhat independent of iotools.
